
version: 2.1

jobs:
  build:
    working_directory: /go/src/github.com/S4eedb/arvancloud-go
    docker:
      - image: circleci/golang:1.15.8

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go mod download
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml
      - store_test_results:
          path: /tmp/test-reports

workflows:
  sample:
    jobs:
      - build
