name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOPROXY: "https://proxy.golang.org"
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.4.0
        with:
          version: v1.37.0
          args: --timeout=30m
