name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  GOPROXY: "https://proxy.golang.org"
jobs:
  lint:
   name: Linux Build
   runs-on: ubuntu-latest
   steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: go test -v -race ./...

